### ISSUE TITLE
excerpt display logic

### ISSUE THREAD

**Issue by drewwestphal** [drewwestphal/jococruise-theme#4]
we'd like excerpts to behave the following way on the front page (@paulnotstorm @gregstormd, please comment if you have additions)
## ARTISTS

always show the excerpt even if it is blank. we may not show text for our artists.
## FAQ Questions, News, About section

show the excerpt if it is NOT blank, otherwise show the content
## MAP

always show the full post content, disregard the excerpt (perhaps the way it is coded and the shortness of stuff makes it so that use of the excerpt is already like this.
## Locations of word excerpt in theme as of 16120b2b51fae6ee1fbc4ba3f2f4dacb4f114b0b (files in include/cpt.php excepted)

```
 ./artist_unit.php:13:          <p><?php $excerpt = get_the_excerpt(); echo $excerpt; ?></p>
 ./attachment.php:19:<p class="attachment"><a href="<?php echo wp_get_attachment_url( $post->ID ); ?>" title="<?php the_title(); ?>" rel="attachment"><img src="<?php echo $att_image[0]; ?>" width="<?php echo $att_image[1]; ?>" height="<?php echo $att_image[2]; ?>" class="attachment-medium" alt="<?php $post->post_excerpt; ?>" /></a></p>
 ./attachment.php:24:<div class="entry-caption"><?php if ( !empty( $post->post_excerpt ) ) the_excerpt(); ?></div>
 ./entry-summary.php:2:<?php the_excerpt(); ?>
 ./index.php:251:                       <?php the_excerpt(); ?>
 ./index.php:382:                            $post -> post_excerpt ? get_the_excerpt() : get_the_content());
 ./map-city-logic.php:11:   <div class="map-city-about hidden-xs <?php if ($title_down_under){ echo 'up';}; if ($info_down_under){ echo ' info-up';};?>"><span><?php the_title(); ?></span><?php the_excerpt(); ?></div>
 ./news-unit.php:2:<?php if($post->post_excerpt){
 ./news-unit.php:3: the_excerpt();
 ./page-faq.php:32:                    $post -> post_content ? apply_filters( 'the_content', $post -> post_content) : apply_filters( 'the_excerpt', $post -> post_excerpt));
 ./page-news.php:24:                            <p><?php the_excerpt(); ?></p>
 ./single.php:30:                       <p><?php the_excerpt(); ?></p>
```

**Comment by cmd-kae** [comment]
It looks like most things were behaving as intended (with some items falling back to excerpts just in case it doesn't for some reason have content) but of course please let me know if I missed something. One note about the artists bios on the front page: I believe I was instructed to use content before excerpt so that truncation could be handled easily. (The design calls for a fixed height.) So, I implemented a more link on excerpts based on a character limit, and stopping at the last whole word which is the closest/quickest thing I could think of to the original solution.
